export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const FETCH_PRODUCTS_DONE = 'FETCH_PRODUCTS_DONE';

export const OPEN_POPUP = 'OPEN_POPUP';
export const CLOSE_POPUP = 'CLOSE_POPUP';

export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
